package gui;

import controladores.ControladorRetiros;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class PanelRetiros extends javax.swing.JPanel {

    private final ControladorRetiros controladorRetiros;
    private MainFrame parent;
    JPanel jPanelBar;
    JPanel jPanelPie;

    public PanelRetiros(MainFrame parent) {
        
        this.parent = parent;
        
        controladorRetiros = new ControladorRetiros();
        initComponents();

        jComboBoxDimension.setModel(new javax.swing.DefaultComboBoxModel(
                controladorRetiros.getDimensionesRelacionadas("Retiros")));
        jComboBoxAtributo.setModel(new javax.swing.DefaultComboBoxModel(
                controladorRetiros.getAtributosInteresantes(jComboBoxDimension.getSelectedItem().toString())));
        jComboBoxHechos.setModel(new javax.swing.DefaultComboBoxModel(
                controladorRetiros.getAtributosInteresantes("Retiros")));

//        imagen.setIcon(new ImageIcon("imagenes/retiros.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxDimension = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxAtributo = new javax.swing.JComboBox();
        jButtonPieJoin = new javax.swing.JButton();
        jButtonBarJoin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonBar1 = new javax.swing.JButton();
        jButtonPie1 = new javax.swing.JButton();
        jComboBoxHechos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxDimension1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxAtributo2 = new javax.swing.JComboBox();
        jButtonBarJoin1 = new javax.swing.JButton();
        jComboBoxDimension2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jPanelGrafica = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 650));
        setLayout(new java.awt.BorderLayout());

        jPanelMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, null, null));
        jPanelMenu.setLayout(new java.awt.GridLayout(3, 1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("dos"));

        jComboBoxDimension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDimensionActionPerformed(evt);
            }
        });

        jLabel2.setText("Dimension");

        jLabel3.setText("Atributo");

        jComboBoxAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAtributoActionPerformed(evt);
            }
        });

        jButtonPieJoin.setText("Pie");
        jButtonPieJoin.setPreferredSize(new java.awt.Dimension(60, 30));
        jButtonPieJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPieJoinActionPerformed(evt);
            }
        });

        jButtonBarJoin.setText("Bar");
        jButtonBarJoin.setPreferredSize(new java.awt.Dimension(60, 30));
        jButtonBarJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBarJoinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonPieJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jButtonBarJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxDimension, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxAtributo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBarJoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPieJoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("uno"));

        jButtonBar1.setText("Bar");
        jButtonBar1.setPreferredSize(new java.awt.Dimension(60, 30));
        jButtonBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBar1ActionPerformed(evt);
            }
        });

        jButtonPie1.setText("Pie");
        jButtonPie1.setPreferredSize(new java.awt.Dimension(60, 30));
        jButtonPie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPie1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Atributo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPie1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxHechos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxHechos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelMenu.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("tres"));
        jPanel4.setLayout(null);

        jComboBoxDimension1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDimension1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxDimension1);
        jComboBoxDimension1.setBounds(18, 56, 224, 28);

        jLabel5.setText("Dimension");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(18, 91, 224, 18);

        jLabel6.setText("Atributo");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(18, 149, 224, 18);

        jComboBoxAtributo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAtributo2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxAtributo2);
        jComboBoxAtributo2.setBounds(18, 173, 224, 28);

        jButtonBarJoin1.setText("Bar");
        jButtonBarJoin1.setPreferredSize(new java.awt.Dimension(60, 30));
        jButtonBarJoin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBarJoin1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonBarJoin1);
        jButtonBarJoin1.setBounds(18, 207, 236, 30);

        jComboBoxDimension2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDimension2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxDimension2);
        jComboBoxDimension2.setBounds(18, 115, 224, 28);

        jLabel7.setText("Hecho");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(18, 32, 224, 18);

        jPanelMenu.add(jPanel4);

        add(jPanelMenu, java.awt.BorderLayout.WEST);

        jPanelGrafica.setName(""); // NOI18N
        jPanelGrafica.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new java.awt.BorderLayout());

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon("/home/gustavo/PROGRAMMING/DESKTOP/DESCUBRIMIENTO_DE_CONOCIMIENTO_EN_BASES_DE_DATOS/Colmovil_DWH/imagenes/retiros.jpg")); // NOI18N
        jPanel1.add(imagen, java.awt.BorderLayout.CENTER);

        jPanelGrafica.add(jPanel1, "imagen");

        add(jPanelGrafica, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPie1ActionPerformed

        String[][] matrizCausas = controladorRetiros.reporteUnParametroPie(
            jComboBoxHechos.getSelectedItem().toString());
        PieChart pieChart = new PieChart("Retiros y Causas", matrizCausas);
        jPanelPie = pieChart.getChartPanel();
        jPanelGrafica.add(jPanelPie, "jPanelPie");
        CardLayout cl = (CardLayout) (jPanelGrafica.getLayout());
        cl.show(jPanelGrafica, (String) "jPanelPie");
        parent.pack();
    }//GEN-LAST:event_jButtonPie1ActionPerformed

    private void jButtonBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBar1ActionPerformed
        String[][] matrizCausas = controladorRetiros.reporteUnParametroBarra(
            jComboBoxHechos.getSelectedItem().toString());
        BarChart barChart = new BarChart("Retiros y Causas", matrizCausas);
        jPanelBar = barChart.getChartPanel();
        jPanelGrafica.add(jPanelBar, "jPanelBar");
        CardLayout cl = (CardLayout) (jPanelGrafica.getLayout());
        cl.show(jPanelGrafica, (String) "jPanelBar");
        parent.pack();

    }//GEN-LAST:event_jButtonBar1ActionPerformed

    private void jButtonBarJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBarJoinActionPerformed

        String[][] matrizCausas = controladorRetiros.reporteUnParametroJoinBarra(
            jComboBoxDimension.getSelectedItem().toString(),
            jComboBoxAtributo.getSelectedItem().toString());
        BarChart barChart = new BarChart("Retiros y Causas", matrizCausas);
        jPanelBar = barChart.getChartPanel();
        jPanelGrafica.add(jPanelBar, "jPanelBar");
        CardLayout cl = (CardLayout) (jPanelGrafica.getLayout());
        cl.show(jPanelGrafica, (String) "jPanelBar");
        parent.pack();
    }//GEN-LAST:event_jButtonBarJoinActionPerformed

    private void jButtonPieJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPieJoinActionPerformed

        String[][] matrizCausas = controladorRetiros.reporteUnParametroJoinPie(
            jComboBoxDimension.getSelectedItem().toString(),
            jComboBoxAtributo.getSelectedItem().toString());
        PieChart pieChart = new PieChart("Retiros y Causas", matrizCausas);
        jPanelPie = pieChart.getChartPanel();
        jPanelGrafica.add(jPanelPie, "jPanelPie");
        CardLayout cl = (CardLayout) (jPanelGrafica.getLayout());
        cl.show(jPanelGrafica, (String) "jPanelPie");
        parent.pack();
    }//GEN-LAST:event_jButtonPieJoinActionPerformed

    private void jComboBoxAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAtributoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAtributoActionPerformed

    private void jComboBoxDimensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDimensionActionPerformed
        jComboBoxAtributo.setModel(new javax.swing.DefaultComboBoxModel(
            controladorRetiros.getAtributosInteresantes(jComboBoxDimension.getSelectedItem().toString())));
    }//GEN-LAST:event_jComboBoxDimensionActionPerformed

    private void jComboBoxDimension1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDimension1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDimension1ActionPerformed

    private void jComboBoxAtributo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAtributo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAtributo2ActionPerformed

    private void jButtonBarJoin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBarJoin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBarJoin1ActionPerformed

    private void jComboBoxDimension2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDimension2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDimension2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButtonBar1;
    private javax.swing.JButton jButtonBarJoin;
    private javax.swing.JButton jButtonBarJoin1;
    private javax.swing.JButton jButtonPie1;
    private javax.swing.JButton jButtonPieJoin;
    private javax.swing.JComboBox jComboBoxAtributo;
    private javax.swing.JComboBox jComboBoxAtributo2;
    private javax.swing.JComboBox jComboBoxDimension;
    private javax.swing.JComboBox jComboBoxDimension1;
    private javax.swing.JComboBox jComboBoxDimension2;
    private javax.swing.JComboBox jComboBoxHechos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelGrafica;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
