/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controladores.ControladorRetiros;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author gustavo
 */
public class panelRetiros extends javax.swing.JPanel {
    private final ControladorRetiros controladorRetiros;
    private JFrame main;
    JPanel jPanelBar;
    JPanel jPanelPie;

    /**
     * Creates new form panelRetiros
     */
    public panelRetiros(JFrame main) {
        this.main = main;
        controladorRetiros = new ControladorRetiros();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelGrafica = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanelMenu.setLayout(new javax.swing.BoxLayout(jPanelMenu, javax.swing.BoxLayout.PAGE_AXIS));

        jButton1.setText("Causa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButton1);

        jButton2.setText("Consulta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButton2);

        add(jPanelMenu, java.awt.BorderLayout.WEST);

        jPanelGrafica.setName(""); // NOI18N
        jPanelGrafica.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Imagen");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanelGrafica.add(jPanel1, "imagen");

        add(jPanelGrafica, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String[][] matrizCausas = controladorRetiros.reporteCausa();
        PieChart pieChart = new PieChart("Retiros y Causas", matrizCausas);
        jPanelPie = pieChart.getChartPanel();
        jPanelGrafica.add(jPanelPie, "jPanelPie");
        CardLayout cl = (CardLayout)(jPanelGrafica.getLayout());
       cl.show(jPanelGrafica, (String)"jPanelPie");
       main.pack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String[][] matrizCausas = controladorRetiros.reporteCausaEstrato();
        BarChart barChart = new BarChart("Retiros y Causas", matrizCausas);
        jPanelBar = barChart.getChartPanel();
        jPanelGrafica.add(jPanelBar, "jPanelBar");
        CardLayout cl = (CardLayout)(jPanelGrafica.getLayout());
       cl.show(jPanelGrafica, (String)"jPanelBar");
       main.pack();

    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGrafica;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
